# Streamlit Cloud Secrets Configuration
# This file should NOT be committed to version control
# Add these secrets in Streamlit Cloud's secrets management interface

# Required API Keys
GROQ_API_KEY = "your-groq-api-key-here"
SERPER_API_KEY = "your-serper-api-key-here" 
GEMINI_API_KEY = "your-gemini-api-key-here"

# Instructions:
# 1. Go to your Streamlit Cloud app settings
# 2. Navigate to "Secrets" section
# 3. Copy the content above and paste it there
# 4. Replace the placeholder values with your actual API keys from GitHub secrets
